### ISSUE TITLE
Update node runtime to node12

### ISSUE THREAD

**Issue by ayusun** [simalexan/sns-subscriber-lambda-s3#1]
Hi,
I was trying to use this repository to deploy a lambda function because nodejs 8 is no longer supported. Will you be able to update the runtime to node12?

Thanks

**Comment by simalexan** [comment]
Hi @ayusun, sure, no problem I will do that today. Will ping you here

**Comment by ayusun** [comment]
Thanks, much appreciated 🙇‍♂️

**Comment by simalexan** [comment]
Hi @ayusun its updated both here and on the AWS Serverless Application Repository. Hope you find it useful. I'll be closing this issue now
